# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0093_auto_20241201_1234'),  # Replace with the actual latest migration
    ]

    operations = [
        migrations.CreateModel(
            name='SensorMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(help_text='Name/identifier of the sensor', max_length=100)),
                ('sensor_type', models.CharField(choices=[('camera', 'Camera'), ('lidar', 'LiDAR'), ('radar', 'Radar'), ('imu', 'IMU'), ('gps', 'GPS')], help_text='Type of sensor', max_length=50)),
                ('modality', models.CharField(blank=True, help_text='Sensor modality (e.g., rgb, depth, etc.)', max_length=50)),
                ('intrinsic_matrix', models.JSONField(blank=True, help_text='Camera intrinsic matrix', null=True)),
                ('extrinsic_matrix', models.JSONField(blank=True, help_text='Sensor extrinsic matrix (pose relative to ego)', null=True)),
                ('distortion_coefficients', models.JSONField(blank=True, help_text='Camera distortion coefficients', null=True)),
                ('resolution', models.JSONField(blank=True, help_text='Sensor resolution [width, height]', null=True)),
                ('field_of_view', models.JSONField(blank=True, help_text='Field of view parameters', null=True)),
                ('frequency', models.FloatField(blank=True, help_text='Sensor capture frequency in Hz', null=True)),
                ('timestamp_offset', models.FloatField(default=0.0, help_text='Timestamp offset relative to master clock')),
                ('additional_metadata', models.JSONField(blank=True, help_text='Additional sensor-specific metadata', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_metadata', to='engine.data')),
            ],
            options={
                'indexes': [models.Index(fields=['data', 'sensor_type'], name='engine_sens_data_id_sensor_typ_idx')],
            },
        ),
        migrations.CreateModel(
            name='EgoPose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.PositiveIntegerField(help_text='Frame number this pose corresponds to')),
                ('translation', models.JSONField(help_text='3D translation [x, y, z] in global coordinates')),
                ('rotation', models.JSONField(help_text='Rotation quaternion [w, x, y, z] in global coordinates')),
                ('timestamp', models.BigIntegerField(blank=True, help_text='Timestamp in microseconds', null=True)),
                ('coordinate_system', models.CharField(default='global', help_text='Coordinate system reference frame', max_length=50)),
                ('pose_source', models.CharField(choices=[('gps_imu', 'GPS+IMU'), ('slam', 'SLAM'), ('motion_capture', 'Motion Capture'), ('manual', 'Manual'), ('other', 'Other')], default='other', help_text='Source of pose estimation', max_length=50)),
                ('pose_confidence', models.FloatField(blank=True, help_text='Pose confidence score [0-1]', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ego_poses', to='engine.data')),
            ],
            options={
                'ordering': ['frame_id'],
                'indexes': [
                    models.Index(fields=['data', 'frame_id'], name='engine_egop_data_id_frame_i_idx'),
                    models.Index(fields=['data', 'timestamp'], name='engine_egop_data_id_timesta_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='sensormetadata',
            constraint=models.UniqueConstraint(fields=('data', 'sensor_name'), name='engine_sensormetadata_data_sensor_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='egopose',
            constraint=models.UniqueConstraint(fields=('data', 'frame_id'), name='engine_egopose_data_frame_id_unique'),
        ),
    ]